spring:
  datasource:
    url: jdbc:mysql://10.1.28.41:3306/remoteRoot
    username: remoteRoot
    password: R00t!20250409
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    #    邮箱官网地址
    host: smtp.163.com
    username: x1815097512@163.com
    password: JFTFLf9Q7aXdPvTU
  redis:
    host: 10.1.28.41
    port: 6379
    password: 
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
      file-size-threshold: 2KB  # 超过此大小的文件会被写入磁盘而非内存
      location: ${java.io.tmpdir}  # 显式指定临时目录
      resolve-lazily: true  # 仅在需要访问文件时才解析multipart请求

jwt:
  secret: your-secret-key-here-must-be-at-least-256-bits-long
  expiration: 86400 # 24小时

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  tomcat:
    connection-timeout: 600000  # 10分钟（毫秒）
    max-http-form-post-size: 100MB
    max-swallow-size: -1  # 禁用swallow，让客户端直接处理中断
    max-connections: 8192  # 增加最大连接数
    accept-count: 100  # 等待队列长度
    threads:
      max: 200  # 最大工作线程数
      min-spare: 10  # 最小工作线程数