spring:
  datasource:
    url: jdbc:mysql://10.1.26.249:3306/remoteRoot
    username: remoteRoot
    password: R00t!20250409
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    #    邮箱官网地址
    host: smtp.163.com
    username: x1815097512@163.com
    password: JFTFLf9Q7aXdPvTU
  redis:
    host: 10.1.26.249
    port: 6379
    password: 
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

jwt:
  secret: your-secret-key-here-must-be-at-least-256-bits-long
  expiration: 86400 # 24小时

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl