spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    #    邮箱官网地址
    host: smtp.163.com
    username: x1815097512@163.com
    password: JFTFLf9Q7aXdPvTU
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl